[package]
name = "dbus-bus-config"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
quick-xml = { version = "0.36.2", features = ["serialize"] }
serde = { version = "1.0.210", features = ["derive"] }
